config/routes.rb
Rails.application.routes.draw do

    devise_for :users, :controllers => { :registrations => 'users/registrations'}

    root 'home#index'

    get 'about', to: 'home#about'

    get 'contact', to: 'home#contact'

    get 'job_offers_candidate', to: 'recruits#job_offers_candidate'

    get 'jobs_offered_company', to: 'recruits#jobs_offered_company'

    resources :recruits

    resources :candidates

    resources :postings

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_footer.html.erb
<!--Footer-->
<footer id="footer" class="footer">
  <div class="container text-center">

  <ul class="social-links">
    <li><a href="#link"><i class="fa fa-twitter fa-fw"></i></a></li>
    <li><a href="#link"><i class="fa fa-facebook fa-fw"></i></a></li>
    <li><a href="#link"><i class="fa fa-google-plus fa-fw"></i></a></li>
    <li><a href="#link"><i class="fa fa-dribbble fa-fw"></i></a></li>
    <li><a href="#link"><i class="fa fa-linkedin fa-fw"></i></a></li>
  </ul>
    ©2016 FreeLancer Xchange Pte Ltd. All rights reserved
    <div class="credits">
        <!--
            All the links in the footer should remain intact.
            You can delete the links only if you purchased the pro version.
            Licensing information: https://bootstrapmade.com/license/
            Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Mentor
        -->
        Designed by <a href="https://bootstrapmade.com/">Free Bootstrap Themes</a>
    </div>
  </div>
</footer>
<!--/ Footer-->

app/views/partials/_header.html.erb
<header>
  <!--Navigation bar-->

  <!--/ Modal box-->
  <% if user_signed_in? %>

  <!-- USER -->

  <<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

     <a class="navbar-brand" href="/">Freelancer<span> Xchange</span></a>

      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Browse", postings_path %></li>

        <% if current_user.user_type == "Freelancer" %>
            <li> <%= link_to "Jobs Offer", job_offers_candidate_path %> </li>
        <%else %>
            <li> <%= link_to "Jobs Offered", jobs_offered_company_path %> </li>
        <% end %>

        <li><a href="/about">About Us</a></li>
        <!-- USER -->
        <li><ul class="nav navbar-nav navbar-right">
                  <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                          <span class="glyphicon glyphicon-user"></span>
                          <strong></strong>
                          <span class="glyphicon glyphicon-chevron-down"></span>
                      </a>
                      <ul class="dropdown-menu">
                          <li>
                              <div class="navbar-login">
                                  <div class="row">
                                      <div class="col-lg-4">
                                          <p class="text-center">
                                              <span class="glyphicon glyphicon-user icon-size"></span>
                                          </p>
                                      </div>
                                      <div class="col-lg-8">
                                            <p class="text-left"><h4 class="user"><%= current_user.user_type  %></h4></p>
                                          <p class="text-left"><strong><%= current_user.username %></strong></p>
                                          <p class="text-left small"><%= current_user.email %></p>

                                      </div>
                                  </div>
                              </div>
                          </li>
                          <li class="divider navbar-login-session-bg"></li>

                          <li><%= link_to edit_user_registration_path, :class => "dropdowntext" do %>Your Personal Profile
                            <!-- <span class="badge pull-right">5</span> --><span class="glyphicon glyphicon-user pull-right"></span>
                            <% end %>
                          </li>

<% if current_user.user_type == "Freelancer" %>

              <li class="divider"></li>

      <% if current_user.name.blank? %>

      <li class: "post"><%= link_to edit_user_registration_path, :class => "dropdowntext",disabled: true, title: 'Please update Personal Profile first before creating a Job Profile' do %>Create Job Profile
        <!-- <span class="badge pull-right">5</span> --><span class="glyphicon glyphicon-pencil pull-right"></span>
        <% end %>
        </li>


      <% else %>
                <% if current_user.candidate.present? %>

                <li><%= link_to candidate_path id: current_user.candidate.id, class: "dropdowntext" do %>Your Job Profile
                <!-- <span class="badge pull-right">5</span> --><span class="glyphicon glyphicon-list-alt pull-right"></span>
                <% end %>
                </li>


                <% else %>

                <li><%= link_to new_candidate_path, :class => "dropdowntext" do %>Create Job Profile
                  <!-- <span class="badge pull-right">5</span> --><span class="glyphicon glyphicon-pencil pull-right"></span>
                  <% end %>
                  </li>


                <% end %>
    <% end %>

<% else %>

<% end %>

              <!-- <li class="divider"></li>
              <li><a href="#">Messages <span class="badge pull-right"> 42 </span></a></li> -->
                      </ul>
                  </li>
              </ul>
            </li>


        <li class="btn-trial"><%= link_to 'Sign out', '/users/sign_out', :method => :delete %></li>

      </ul>
      </div>
    </div>
  </nav>







  <!-- END OF USER -->

<% else %>


  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Freelancer<span> Xchange</span></a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Browse", postings_path %></li>
        <li><a href="/about">About Us</a></li>
        <li><%= link_to "Sign In",new_user_session_path%></li>
        <li class="btn-trial"><%= link_to "Sign Up",new_user_registration_path%></li>
      </ul>
      </div>
    </div>
  </nav>
  <!--/ Navigation bar-->

<% end %>

</header>