config/routes.rb
Rails.application.routes.draw do

    devise_for :users, :controllers => { :registrations => 'users/registrations'}

    root 'home#index'

    get 'about', to: 'home#about'

    get 'contact', to: 'home#contact'

    get 'job_offers_candidate', to: 'recruits#job_offers_candidate'

    get 'jobs_offered_company', to: 'recruits#jobs_offered_company'

    resources :recruits

    resources :candidates

    resources :postings

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/posting.rb
class Posting < ApplicationRecord

  belongs_to :candidate
  # belongs_to :candidate, foreign_key: 'cand_info_id'

  # belongs_to :cand_info, class_name: 'Candidate', primary_key: 'id'

  has_many :recruits

end

app/controllers/postings_controller.rb
class PostingsController < ApplicationController

  def index
    # @postings = Posting.all.reverse_order
    @postings = Candidate.where('status > ?', 0).reverse_order

    respond_to do |format|
      format.html
      format.json { render json: @postings }
    end
  end


  def show
    @posting = Posting.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @posting }
    end
  end


  def new
    @posting = Posting.new
    @candiates=current_user.candidates
  end


  def create
    # @candidate = Candidate.find(params[:candidate_id])
    # @new_posting = Posting.new()
    # @new_posting.candidate_id = @candidate.id

    if current_user.candidate.posting.present?

      @candidate = Candidate.find(params[:candidate_id])
      # @new_posting = Posting.new()
      # @new_posting.candidate_id = @candidate.id
      @candidate.status = 1
      @candidate.save

      respond_to do |format|
        if @candidate.save
          format.html { redirect_to candidate_path id: @candidate.id }
          format.json { render :show, status: :ok, location: @candidate }
        else
          format.html { render :new }
          format.json { render json: @new_posting.errors, status: :unprocessable_entity }
        end
        end

  else

    @candidate = Candidate.find(params[:candidate_id])
    @new_posting = Posting.new()
    @new_posting.candidate_id = @candidate.id
    @new_posting.save
    @candidate.status = 1
    @candidate.save
    @new_posting.errors.full_messages

    respond_to do |format|
      if @new_posting.save
        format.html { redirect_to candidate_path id: @candidate.id }
        format.json { render :show, status: :ok, location: @new_posting }
      else
        format.html { render :new }
        format.json { render json: @new_posting.errors, status: :unprocessable_entity }
      end
    end
    end
  end


  def destroy
    @candidate = Candidate.find(params[:id])
    # @posting= Posting.find(params[:candidate_id])
    # @posting = Posting.find(params[:id])
    # @posting.candidate_id = @candidate.id

    @candidate.status = 0
    @candidate.save
    # @posting.destroy
    respond_to do |format|
      format.html { redirect_to candidate_path, notice: 'You have successfully removed your posting' }
      format.json { head :no_content }
    end
  end

end

app/helpers/postings_helper.rb
module PostingsHelper
end

app/views/postings/index.html.erb
<div class="container">

  <div class="heading heading-contact">
    <div class="col-lg-12">
      <div class="section-heading">
        <h2>Browse our highest-rated developers</h2>
        <br>
      </div>
    </div>
  </div>

  <!-- SEARCH BAR -->
  <!-- <div class="col-md-12">
    <form action="#" method="get">
      <div class="input-group">
        <input class="form-control" id="system-search" name="q" placeholder="Search all postings..." required>
        <span class="input-group-btn">
            <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
        </span>
      </div>
    </form>
    <br>
    <br>
  </div> -->

	<div class="row" align="center">

      <% @postings.each do |posting| %>
		<div class="col-xs-12 col-sm-12 col-md-6 col-lg-3">
            <div class="boxes">
                <div class="img-upper">

                  <% if posting.photo.present? %>

                      <div class="img-responsive" id="pic-1">
                        <%= image_tag(posting.photo_url, width: 230, height:250, class:'object-fit_cover', alt:'Picture') %>
                      </div>

                  <% else %>

                      <div class="img-responsive" id="pic-1">
                        <img src="http://larics.rasip.fer.hr/wp-content/uploads/2016/04/default-placeholder.png" alt="Picture" width="230" height="250" class="object-fit_cover"/>
                      </div>

                  <% end %>

<!--
                    <img class="img-responsive" src="http://hdwallpapershdpics.com/wp-content/uploads/2016/06/hd-image-3.jpg"> -->
                </div>

                <div class="description">
                    <h2>

                      <% if user_signed_in? %>
                          <%= link_to posting.individual.username, posting_path(posting.posting.id) %>
                      <% else %>
                        <%= posting.individual.username %>
                      <% end %>
                    </h2>


                      <h4 class="product-title">
                        <%= posting.title %>
                      </h2>


                        <h4 class="product-title">
                          Skills: <%= posting.language %>
                        </h2>



                        <h4 class="product-title">
                        Rate: $<%= posting.rate %>/hr
                        </h2>

                        <br>
                    <% if user_signed_in? %>
                        <%= link_to 'View Details', posting_path(posting.posting.id), class:"btn btn-primary" %>
                    <% else %>

                    <% end %>

                </div>
            </div>

		</div>
    <% end %>
	</div>


</div>

app/views/postings/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-offset-3 col-md-8 col-lg-offset-3 col-lg-7">
    	 <div class="well profile">
            <div class="col-sm-12">
                <div class="col-xs-12 col-sm-8">
                    <h2><%= @posting.candidate.individual.username %></h2>

                    <p><strong> <%= @posting.candidate.title %>  </strong></p>

                    <p><strong>Language: </strong>
                        <span class="tags"> <%= @posting.candidate.language %> </span>
                    </p>

                    <p><strong>Description: </strong>
                        <span> <%= @posting.candidate.description %> </span>
                    </p>

                    <p><strong>Rate ($/hr): </strong>
                        <span> <%= @posting.candidate.rate %> </span>
                    </p>

                </div>

                <div class="col-xs-12 col-sm-4 text-center">
                    <figure>

                        <% if @posting.candidate.photo.present? %>

                            <td class="tab-pane active" id="pic-1">
                              <%= image_tag(@posting.candidate.photo_url, width: 150, height:125, class:'object-fit_cover', alt:'Picture') %>
                            </td>

                        <% else %>

                            <td class="tab-pane active" id="pic-1">
                              <img src="http://larics.rasip.fer.hr/wp-content/uploads/2016/04/default-placeholder.png" alt="" width="150" height="125" class="object-fit_cover"/>
                            </td>

                        <% end %>

                            <p>Rating:
                              <a href="#">
                                  <span class="fa fa-star"></span>
                              </a>
                              <a href="#">
                                  <span class="fa fa-star"></span>
                              </a>
                              <a href="#">
                                  <span class="fa fa-star"></span>
                              </a>
                              <a href="#">
                                  <span class="fa fa-star"></span>
                              </a>
                              <a href="#">
                                   <span class="fa fa-star-o"></span>
                              </a>
                            </p>
                        </figcaption>
                    </figure>
                </div>
            </div>


            <div class="col-xs-12 divider text-center">
                <div class="col-xs-12 col-sm-4 emphasis">
                    <!-- <h2><strong>  </strong></h2>
                    <p><small>   </small></p>
                    <button class="btn btn-success btn-block"><span class="fa fa-plus-circle"></span> Follow </button> -->
                </div>


								<% if current_user.user_type == 'Hirer' %>

									  <div class="col-xs-12 col-sm-4 emphasis">
		                    <h2><strong>   </strong></h2>
		                    <p><small>   </small></p>
		                    <!-- <button class="btn btn-info btn-block"><span class="fa fa-user"></span> Offer Job </button> -->

												<%= form_tag new_recruit_path, method: :get do %>
													<%= hidden_field_tag :posting_id, @posting.id %></td>

													<%= button_tag(type: 'submit', class: "btn btn-info btn-block") do %>
													<i class="fa fa-user">&nbsp;</i> Offer Job
													<% end %>
				                	</div>
												<% end %>

		                </div>
								<% end %>


								<div class="col-xs-12 col-sm-4 emphasis">
                    <h2><strong>   </strong></h2>
                    <p><small>   </small></p>
                    <!-- <div class="btn-group dropup btn-block">
                      <button type="button" class="btn btn-primary"><span class="fa fa-gear"></span> Options </button>
                      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                        <span class="caret"></span>
                        <span class="sr-only">Toggle Dropdown</span>
                      </button>
                      <ul class="dropdown-menu text-left" role="menu">
                        <li><a href="#"><span class="fa fa-envelope pull-right"></span> Send an email </a></li>
                        <li><a href="#"><span class="fa fa-list pull-right"></span> Add or remove from a list  </a></li>
                        <li class="divider"></li>
                        <li><a href="#"><span class="fa fa-warning pull-right"></span>Report this user for spam</a></li>
                        <li class="divider"></li>
                        <li><a href="#" class="btn disabled" role="button"> Unfollow </a></li>
                      </ul>
                    </div> -->
                </div>
            </div>
    	 </div>
		</div>
	</div>
</div>


<!-- <div class="container">

  <div class="row">

    <div class="heading heading-contact">
      <div class="col-lg-12">
        <div class="section-heading">
          <h1>Detailed Postings</h1>
        </div>
      </div>
    </div>

    <div class="col-md-12">
      <br>
      <table class="table table-list-search">

        <thead>
          <tr>
            <th>Photo</th>
            <th>Username</th>
            <th>Title</th>
            <th>Languages</th>
            <th>Description</th>
            <th>Rate ($/hr)</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
            <tr>
              <% if @posting.candidate.photo.present? %>

                  <td class="tab-pane active" id="pic-1">
                    <%= image_tag(@posting.candidate.photo_url, width: 150, height:125, class:'object-fit_cover', alt:'Picture') %>
                  </td>

              <% else %>

                  <td class="tab-pane active" id="pic-1">
                    <img src="http://larics.rasip.fer.hr/wp-content/uploads/2016/04/default-placeholder.png" alt="" width="150" height="125" class="object-fit_cover"/>
                  </td>

              <% end %>

              <td> <%= @posting.candidate.individual.username %> </td>
              <td> <%= @posting.candidate.title %> </td>
              <td> <%= @posting.candidate.language %> </td>
              <td> <%= @posting.candidate.description %> </td>
              <td> <%= @posting.candidate.rate %> </td>
              <td> TO BE INSERTED !!! </td>
            </tr>
            <tr>
              <td> </td>
              <td> </td>
              <td> </td>
              <td> </td>
              <td> </td>
              <td> </td>
              <td> </td>
            </tr>
        </tbody>
      </table>
    </div>

  </div>
</div> -->