config/routes.rb
Rails.application.routes.draw do

    devise_for :users, :controllers => { :registrations => 'users/registrations'}

    root 'home#index'

    get 'about', to: 'home#about'

    get 'contact', to: 'home#contact'

    get 'job_offers_candidate', to: 'recruits#job_offers_candidate'

    get 'jobs_offered_company', to: 'recruits#jobs_offered_company'

    resources :recruits

    resources :candidates

    resources :postings

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/candidate.rb
class Candidate < ApplicationRecord

    has_one :posting
    # has_one :posting, foreign_key: 'cand_info_id'

    belongs_to :individual, class_name: 'User', primary_key: 'id'
    # belongs_to :candidate, class_name: 'User', primary_key: 'id'

    # belongs_to :cand/individual!!!!!, class_name: 'User', primary_key: 'id'
    # belongs_to :cand, class_name: 'User', primary_key: 'id' - as discussed with Amanda

    mount_uploader :photo, PictureUploader

    validates :title, length: { maximum: 25 }, presence: true
    validates :language, presence: true
    validates :description, length: { maximum: 500 }, presence: true
    validates :rate, numericality: { only_integer: true }, presence: true

end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

  def index
    @candidates=Candidate.all

    respond_to do |format|
      format.html
      format.json { render json: @candidates }
    current_user
    end
  end


  def show
    @candidate = Candidate.find(params[:id])

  end


  def new
  @new_candidate = Candidate.new
  unless user_signed_in?
  redirect_to new_user_session_path, :alert => "Please log in to create job profile"
  end
  end


  def create
      current_user
      @new_candidate = Candidate.new()
      @new_candidate.title = params[:candidate][:title]
      @new_candidate.language = params[:candidate][:language]
      @new_candidate.description = params[:candidate][:description]
      @new_candidate.rate = params[:candidate][:rate]
      @new_candidate.status = params[:candidate][:status]
      @new_candidate.photo = params[:candidate][:photo]
      @new_candidate.individual_id = current_user.id
      @new_candidate.errors.full_messages

      respond_to do |format|
        if @new_candidate.save
          format.html { redirect_to candidate_path id: @new_candidate.id, notice: 'Your profile is successfully created.' }
          format.json { render :show, status: :ok, location: @new_candidate }
        else
          format.html { render :new }
          format.json { render json: @new_candidate.errors, status: :unprocessable_entity }
        end
      end
  end


def edit
  @candidate = Candidate.find(params[:id])
  if user_signed_in?
    unless current_user.id == @candidate.individual_id
    redirect_to root_path, :alert => "You can only edit your profile"
    end
  else
    redirect_to new_user_session_path, :alert => "Please log in to edit"
  end
  rescue ActiveRecord::RecordNotFound
  redirect_to root_url, :alert => "Record not found."
end


def update
  @candidate = Candidate.find(params[:id])
  respond_to do |format|
    if @candidate.update(candidate_params)
      format.html { redirect_to candidate_path id: @candidate.id, notice: 'Your profile was successfully updated.' }
      format.json { render :show, status: :ok, location: @candidate }
    else
      format.html { render :edit }
      format.json { render json: @candidate.errors, status: :unprocessable_entity }
    end
  end
end


  private

  def posted_params
    params.permit(:status)
  end


  def candidate_params
  params.require(:candidate).permit(:title,:language, :description, :rate, :status, :photo, :individual_id)
  end

end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/edit.html.erb
<div class="container">

  <div class="heading heading-contact">
    <div class="col-lg-12">
      <div class="section-heading">
        <h2>Edit Current Job Profile</h2>

        <p>When you submit a proposal, clients review your profile to decide if your skills and experience match what they are looking for. It's time to create a profile with the jobs you want in mind. This is your opportunity to market your freelance business to clients.</p>

      </div>
    </div>
  </div>

  <div class="heading col-lg-12">
  </div>



  <div class="row">
    <div class="col-md-9 personal-info">
        <!-- form for -->
                <%= form_for @candidate do |f| %>

                <% if @candidate.errors.any? %>

                <div class="alert alert-error alert-danger">
                <button type="button" class="close" data-dismiss="alert">x</button>

                <div id="error_explanation">
                    <h4><%= pluralize(@candidate.errors.count, "error") %>
                        prohibited this profile from being saved:</h4>

                    <ul>
                        <% @candidate.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                        <% end %>
                    </ul>
                </div>
                </div>
                <% end %>

                <form class="form-horizontal" role="form">


                <!-- Text input-->
                <div class="form-group">
                    <%= f.label :'Title' , class:"col-lg-3 control-label" %>
                    <div class="col-md-8">
                        <%= f.text_field :title, autofocus: true, class: "form-control" , placeholder:"Brief description e.g. Full Stack Developer", required: true %>
                        <br/>
                    </div>
                </div>
                <br>
                <br>
                <!-- Text input-->

                <div class="form-group">

                  <%= f.label :'Progamming Language', class:"col-lg-3 control-label" %>
                  <div class="col-md-8">

                    <%= f.select :language, ['', 'CSS', 'RUBY ON RAILS', 'HTML', 'JAVASCRIPT', 'PYTHON', 'PHP', 'Java', 'C' ], class: "form-control", required: true %>

                    </div>
                </div>
                    <!--
                                      <div class="container">

                        <div class="row">
                            <div class="form-group">
                                <div class="items-collection">

                                    <div class="items col-xs-6 col-sm-3 col-md-3 col-lg-3">
                                        <div class="info-block block-info clearfix">
                                            <div data-toggle="buttons" class="btn-group bizmoduleselect">
                                                <label class="btn btn-default">
                                                    <div class="itemcontent">
                                                      <input type="checkbox" name="language[]" autocomplete="off" value="CSS">

                                                      <h5>CSS</h5>

                                                    </div>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="items col-xs-6 col-sm-3 col-md-3 col-lg-3">
                                        <div class="info-block block-info clearfix">
                                            <div data-toggle="buttons" class="btn-group itemcontent">
                                                <label class="btn btn-default">
                                                    <div class="itemcontent">
                                                        <input type="checkbox" name="language[]" autocomplete="off" value="HTML5">

                                                        <h5>HTML5</h5>
                                                    </div>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="items col-xs-6 col-sm-3 col-md-3 col-lg-3">
                                        <div class="info-block block-info clearfix">
                                            <div data-toggle="buttons" class="btn-group itemcontent">
                                                <label class="btn btn-default">
                                                    <div class="itemcontent">
                                                        <input type="checkbox" name="language[]" autocomplete="off" value="Ruby on Rails">

                                                        <h5>Ruby on Rails</h5>
                                                    </div>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="items col-xs-6 col-sm-3 col-md-3 col-lg-3">
                                        <div class="info-block block-info clearfix">
                                            <div data-toggle="buttons" class="btn-group itemcontent">
                                                <label class="btn btn-default">
                                                    <div class="itemcontent">
                                                        <input type="checkbox" name="language[]" autocomplete="off" value="Python">

                                                        <h5>Python</h5>
                                                    </div>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="items col-xs-6 col-sm-3 col-md-3 col-lg-3">
                                        <div class="info-block block-info clearfix">
                                            <div data-toggle="buttons" class="btn-group itemcontent">
                                                <label class="btn btn-default">
                                                    <div class="itemcontent">
                                                        <input type="checkbox" name="language[]" autocomplete="off" value="Javascript">

                                                        <h5>Javascript</h5>
                                                    </div>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="items col-xs-6 col-sm-3 col-md-3 col-lg-3">
                                        <div class="info-block block-info clearfix">
                                            <div data-toggle="buttons" class="btn-group itemcontent">
                                                <label class="btn btn-default">
                                                    <div class="itemcontent">
                                                        <input type="checkbox" name="language[]" autocomplete="off" value="PHP">
                                                        <h5>PHP</h5>
                                                    </div>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="items col-xs-6 col-sm-3 col-md-3 col-lg-3">
                                        <div class="info-block block-info clearfix">
                                            <div data-toggle="buttons" class="btn-group itemcontent">
                                                <label class="btn btn-default">
                                                    <div class="itemcontent">
                                                        <input type="checkbox" name="language[]" autocomplete="off" value="Java">

                                                        <h5>Java</h5>
                                                    </div>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="items col-xs-6 col-sm-3 col-md-3 col-lg-3">
                                        <div class="info-block block-info clearfix">
                                            <div data-toggle="buttons" class="btn-group itemcontent">
                                                <label class="btn btn-default">
                                                    <div class="itemcontent">
                                                        <input type="checkbox" name="language[]" autocomplete="off" value="Node">

                                                        <h5>Node</h5>
                                                    </div>
                                                </label>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div> -->

                <br>
                <br>
                <br>

                <!-- Text input-->

                <div class="form-group">

                    <%= f.label :'Set Hourly Rate' , class:"col-lg-3 control-label" %>

                    <div class="col-md-4">

                        <%= f.text_field :rate, autofocus: true, class: "form-control" , placeholder: "Hourly Rate e.g. $20/hr", required: true %>
                        <br/>
                    </div>
                </div>


              <br>
              <br>


                <!-- Text input-->
                <div class="form-group">
                    <%= f.label :description , class:"col-lg-3 control-label" %>
                    <div class="col-md-8">
                        <%= f.text_area :description , autofocus: true, class: "form-control" , placeholder: "Detailed description of your profile, skills and experience", required: true %>
                        <br/>
                    </div>
                </div>

                <!-- Text input-->

              <div class="form-group">
                  <%= f.label :'Upload Personal Photo' , class:"col-lg-3 control-label"%>
                  <div class="col-md-8">
                      <%= f.file_field :photo, autofocus: true %>
                      <br/>
                  </div>
              </div>

                <p>
                    <%= f.hidden_field :individual_id, value: current_user.id %>
                </p>

                <p>
                    <%= f.hidden_field :status, value: 0 %>
                </p>

                <div class="form-group">
                    <label class="col-md-3 control-label"></label>
                    <div class="col-md-8">
                        <div class="pull-right">

                            <%= f.submit "Save Changes", Class: "btn btn-success" %>

                            <%= link_to "Cancel", :back, class: "btn btn-default" %>

                        </div>
                    </div>

                </div>


        </form>
        <% end %>
    </div>

</div>
    <!-- /.col-lg-12 -->
</div>
<br>
<br>
<!-- /.row -->

app/views/candidates/show.html.erb
<div class="container">
	<div class="row">

		<h2>How Your Profile Looks</h2>
		<div class="col-md-offset-3 col-md-8 col-lg-offset-3 col-lg-7">

    	 <div class="well profile">
            <div class="col-sm-12">
                <div class="col-xs-12 col-sm-8">
                    <h2><%= current_user.username %></h2>

                    <p><strong> <%= current_user.candidate.title %>  </strong></p>

                    <p><strong>Language: </strong>
                        <span class="tags"> <%= current_user.candidate.language %> </span>
                    </p>

                    <p><strong>Description: </strong>
                        <span> <%= current_user.candidate.description %> </span>
                    </p>

                    <p><strong>Rate ($/hr): </strong>
                        <span> <%= current_user.candidate.rate %> </span>
                    </p>

                </div>

                <div class="col-xs-12 col-sm-4 text-center">
                    <figure>

                        <% if current_user.candidate.photo.present? %>

                            <td class="tab-pane active" id="pic-1">
                              <%= image_tag(current_user.candidate.photo_url, width: 150, height:125, class:'object-fit_cover', alt:'Picture') %>
                            </td>

                        <% else %>

                            <td class="tab-pane active" id="pic-1">
                              <img src="http://larics.rasip.fer.hr/wp-content/uploads/2016/04/default-placeholder.png" alt="" width="150" height="125" class="object-fit_cover"/>
                            </td>

                        <% end %>

                            <p>Rating:
                              <a href="#">
                                  <span class="fa fa-star"></span>
                              </a>
                              <a href="#">
                                  <span class="fa fa-star"></span>
                              </a>
                              <a href="#">
                                  <span class="fa fa-star"></span>
                              </a>
                              <a href="#">
                                  <span class="fa fa-star"></span>
                              </a>
                              <a href="#">
                                   <span class="fa fa-star-o"></span>
                              </a>
                            </p>
                        </figcaption>
                    </figure>
                </div>
            </div>



            <div class="col-xs-12 divider text-center">

							<% if @candidate.status == 0 %>
							<div class="col-xs-12 col-sm-4 emphasis">
									<h2><strong>   </strong></h2>
									<p><small>   </small></p>
									<%= link_to edit_candidate_path, class: "btn btn-info btn-block" do %>
									<i class="fa fa-user">&nbsp;</i> Edit Profile
									<% end %>
							</div>

							<% else %>

							<div class="col-xs-12 col-sm-4 emphasis" >
									<h2><strong>   </strong></h2>
									<p><small>   </small></p>
								<div data-toggle="tooltip" title="Please remove your posting before editing your profile">
									<%= link_to edit_candidate_path, class: "btn btn-info btn-block disabled" do %>
									<i class="fa fa-user">&nbsp;</i> Edit Profile
									<% end %>
								</div>
							</div>

							<% end %>


							<% if @candidate.status == 0 %>
								<!-- <%= @candidate.status %>
								<%= @candidate.id%> -->


								<%= form_tag postings_path, method: :post do %>
									<%= hidden_field_tag :candidate_id, current_user.candidate.id %></td>

	                <div class="col-xs-12 col-sm-5 emphasis">

                    <h2><strong>   </strong></h2>
                    <p><small>   </small></p>

												<%= button_tag(type: 'submit', title: 'Submit Posting', class: "btn btn-success btn-block") do %><i class="fa fa-plus-circle">&nbsp;</i> Post Your Profile
												<% end %>
                	</div>
								<% end %>


							<% else %>
                	<div class="col-xs-12 col-sm-5 emphasis">
                    <h2><strong>   </strong></h2>
                    <p><small>   </small></p>
                    <div class="btn-group dropup btn-block">
<!--

											<%= @candidate.status %>
											<%= @candidate.id %>



												<!-- <%= link_to '', posting_path, class: 'btn btn-danger', method: :delete, data: { confirm: 'This will delete your property. Are you sure?' }%><i class="fa fa-plus-circle"></i> Remove Posting -->
												<%= form_tag posting_path, method: :delete do %>
												<%= hidden_field_tag :candidate_id, current_user.candidate.posting.id %></td>

												<%= button_tag(type: 'submit', title: 'Submit Posting', class: "btn btn-success btn-block") do %><i class="fa fa-remove">&nbsp;</i> Remove Posting
												<% end %>
												<% end %>

                    </div>

                </div>
							<% end %>
            </div>

    	 </div>
		</div>
	</div>
</div>