config/routes.rb
Rails.application.routes.draw do

    devise_for :users, :controllers => { :registrations => 'users/registrations'}

    root 'home#index'

    get 'about', to: 'home#about'

    get 'contact', to: 'home#contact'

    get 'job_offers_candidate', to: 'recruits#job_offers_candidate'

    get 'jobs_offered_company', to: 'recruits#jobs_offered_company'

    resources :recruits

    resources :candidates

    resources :postings

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recruit.rb
class Recruit < ApplicationRecord

  belongs_to :posting
  belongs_to :company, class_name: 'User', primary_key: 'id'

  validates :scope, length: { maximum: 250 }, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true

end

app/controllers/recruits_controller.rb
class RecruitsController < ApplicationController

  def job_offers_candidate
    @current_candidate_individual_info = current_user.candidate

    respond_to do |format|
      format.html
      format.json { render json: @current_candidate_individual_info }
    end
  end


  def update
      @job_offer = Recruit.find(params[:id])
      @job_offer.status = params[:status]
      @job_offer.save

      if current_user.user_type == 'Freelancer'
          respond_to do |format|
            if @job_offer.save
              format.html { redirect_to job_offers_candidate_path, notice: 'You have successfully submitted your chosen action'}
              format.json { render :show, status: :ok, location: @job_offer}
            else
              format.html { render :new }
              format.json { render json: @job_offer.errors, status: :unprocessable_entity }
            end
          end
      else
          respond_to do |format|
            if @job_offer.save
              format.html { redirect_to jobs_offered_company_path, notice: 'You have successfully submitted your chosen action'}
              format.json { render :show, status: :ok, location: @job_offer}
            else
              format.html { render :new }
              format.json { render json: @job_offer.errors, status: :unprocessable_entity }
            end
          end
      end
  end


  def jobs_offered_company
    @offers_sent = current_user.recruits

    respond_to do |format|
      format.html
      format.json { render json: @offers_sent }
    end
  end


  def new
    @new_recruit = Recruit.new
    @posting = Posting.find(params[:posting_id])
  end


  def create
    @new_recruit = Recruit.new
    @new_recruit.status = 0
    @new_recruit.scope = params[:recruit][:scope]
    @new_recruit.start_date = params[:recruit][:start_date]
    @new_recruit.end_date = params[:recruit][:end_date]
    @new_recruit.posting_id = params[:recruit][:posting_id]
    @new_recruit.company_id = current_user.id

    @new_recruit.save
    @new_recruit.errors.full_messages

    respond_to do |format|
      if @new_recruit.save
        format.html { redirect_to postings_path, notice: 'You have successfully submitted your offer'}
        format.json { render :show, status: :ok, location: @new_recruit }
      else
        format.html { render :new }
        format.json { render json: @new_recruit.errors, status: :unprocessable_entity }
      end
    end
  end


end

app/helpers/recruits_helper.rb
module RecruitsHelper
end

app/views/recruits/job_offers_candidate.html.erb
<div class="container">
  <div class="row">
    <div class="heading heading-contact">
      <div class="col-lg-12">
        <div class="section-heading">
          <h2>My Job Offers</h2>
        </div>
      </div>
    </div>
          <!-- In our model, we have assumed one condidate can only have one posting, below condition is to deal with situation where the candidate have created one job profile but have not posted it. May need to refactor if we change model assumption one condidate can have many postings. -->
<% if current_user.name.blank? %>

          <div class="heading col-lg-12">
            <h4>Please <%= link_to edit_user_registration_path do %>create</span>
            <% end %> your personal and job profile.
            </h4>
            <br>
    </div>


<% else %>
  <% if @current_candidate_individual_info.present? %>
    <% if @current_candidate_individual_info.posting.present? %>

                <div class="heading col-lg-12">
                <h4>Title: <%= @current_candidate_individual_info.title %> </h4>
                <h4>Rate ($/hr): <%= @current_candidate_individual_info.rate %> </h4>
                <h4>Date Listed: <%= @current_candidate_individual_info.updated_at.in_time_zone("Singapore").strftime('%d %b %Y') %> </h4>
                <h4>Status:
                  <% if @current_candidate_individual_info.status == 0 %>

                      <span class ="post" >You have not posted your job profile</span>

                  <% else @current_candidate_individual_info.status == 1 %>

                      <span class ="user" >You have posted your job profile</span>

                  <% end %>
                 </h4>
                </div>
                <div class="col-md-12">
                <table class="table table-list-search">
                <thead>
                <tr>
                  <th>Date Offer Made</th>
                  <th>Company Name</th>
                  <th>Contact Name</th>
                  <th>Job Start Date</th>
                  <th>Job End Date</th>
                  <th>Job Scope</th>
                  <!-- <th>Message</th> -->
                  <th>Action</th>
                </tr>
              </thead>

              <tbody>
                  <% @current_candidate_individual_info.posting.recruits.reverse_order.each do |offer_received| %>
                  <tr>
                      <td> <%= offer_received.updated_at.strftime('%d %b %Y') %> </td>
                      <td> <%= offer_received.company.company_name %> </td>
                      <td> <%= offer_received.company.name %> </td>
                      <td> <%= offer_received.start_date.in_time_zone("Singapore").strftime('%d %b %Y') %> </td>
                      <td> <%= offer_received.end_date.in_time_zone("Singapore").strftime('%d %b %Y') %> </td>
                      <td> <%= offer_received.scope %> </td>
                      <!-- <td> Message here!!! </td> -->

                      <% if offer_received.status == 0 %>
                      <td>
                        <div>
                        <%= form_tag recruit_path(offer_received.id), method: :patch do %>
                          <%= hidden_field_tag :status, 2 %>
                        <%= button_tag(type: 'submit', class:"btn btn-info btn-block tip-right", title: 'Accept Offer') do %>
                        <span class="glyphicon glyphicon-send">&nbsp;</span>
                        <span>Accept Offer</span>
                        <% end %>
                        <% end %>
                        </div>

                      <div>
                      <br>
                      <%= form_tag recruit_path(offer_received.id), method: :patch do %>
                          <%= hidden_field_tag :status, 1 %>
                      <%= button_tag(type: 'submit', class:"btn btn-failure btn-block tip-right", title: 'Decline Offer') do %>
                      <span class="glyphicon glyphicon-send">&nbsp;</span>
                      <span>Decline Offer</span>
                      <% end %>
                      <% end %>
                      </div>
                      </td>

                      <% elsif offer_received.status == 1 %>
                      <td>
                        <span class="btn btn-failure btn-block disabled">Declined Job Offer</span>
                      </td>

                      <% elsif offer_received.status == 2 %>
                      <td>
                      <div>
                      <%= form_tag recruit_path(offer_received.id), method: :patch do %>
                        <%= hidden_field_tag :status, 3 %>
                        <%= button_tag(type: 'submit', class:"btn btn-in-progress btn-block tip-right", title: 'Mark as Complete') do %>
                        <span class="glyphicon glyphicon-send">&nbsp;</span>
                        <span>Mark As Complete</span>
                        <% end %>
                      <% end %>
                      </div>
                      </td>

                      <% elsif offer_received.status == 3 %>
                      <td>
                      <span class="btn btn-in-progress btn-block disabled">Pending Completion Confirmation</span>
                      </td>

                      <% else offer_received.status == 4 %>
                      <td>
                      <span class="btn btn-success btn-block disabled">Job Fully Completed</span>
                      </td>
                      <% end %>
                      <% end %>

                    <% else %>

                    <div class="heading col-lg-12">
                    <h4>Please <%= link_to candidate_path id: current_user.candidate.id do %>post</span>
                    <% end %> your job profile.
                    </h4>
                    <br>
                    </div>

                    <% end %>

        </tbody>
      </table>
    </div>

    <% else %>
    <div class="heading col-lg-12">

            <h4>Please <%= link_to new_candidate_path do %>create</span>
            <% end %> your job profile.
            </h4>
            <br>
    </div>
    <% end %>
  <% end %>
  </div>
</div>

app/views/recruits/jobs_offered_company.html.erb
<div class="container">
  <div class="row">

    <div class="heading heading-contact">
      <div class="col-lg-12">
        <div class="section-heading">
          <h2>Jobs Offered</h2>
        </div>
      </div>
    </div>

    <div class="col-md-12">

      <% if @offers_sent.present? %>

      <table class="table table-list-search">
        <thead>
          <tr>
            <th>Date Offer Sent</th>
            <th>Username</th>
            <th>Title</th>
            <th>Skills</th>
            <th>Rate</th>
            <th>Job Start Date</th>
            <th>Job End Date</th>
            <th>Job Scope</th>
             <!-- <th>Message</th> -->
            <th>Status/Action</th>
          </tr>
        </thead>

        <tbody>
            <% @offers_sent.reverse_order.each do |offer_sent| %>
                <tr>
                    <td> <%= offer_sent.updated_at.strftime('%d %b %Y') %> </td>
                    <td> <%= offer_sent.posting.candidate.individual.username %> </td>
                    <td> <%= offer_sent.posting.candidate.title %> </td>
                    <td> <%= offer_sent.posting.candidate.language %> </td>
                    <td> <%= offer_sent.posting.candidate.rate %> </td>
                    <td> <%= offer_sent.start_date.strftime('%d %b %Y') %> </td>
                    <td> <%= offer_sent.end_date.strftime('%d %b %Y') %> </td>
                    <td> <%= offer_sent.scope %> </td>
                    <!-- <td> Message Here!!! </td> -->

                    <% if offer_sent.status == 0 %>
                        <td>
                            <span class="btn btn-info btn-block disabled">Job Offered and Pending Acceptance</span>
                        </td>
                    <% elsif offer_sent.status == 1 %>
                        <td>
                            <span class="btn btn-failure btn-block disabled">Job Offer Declined</span>
                        </td>
                    <% elsif offer_sent.status == 2 %>
                        <td>
                            <span class="btn btn-in-progress btn-block disabled">Job Offer Accepted and In Progress</span>
                        </td>

                    <% elsif offer_sent.status == 3 %>
                        <td>
                            <%= form_tag recruit_path(offer_sent.id), method: :patch do %>
                                <%= hidden_field_tag :status, 4 %>
                                <%= button_tag(type: 'submit', class:"btn btn-in-progress btn-block tip-right", title: 'Confirm Job Completion') do %>
                                <span class="glyphicon glyphicon-send">&nbsp;</span>
                                <span>Confirm Job Completion</span>
                                <% end %>
                            <% end %>
                        </td>

                    <% elsif offer_sent.status == 4 %>
                        <td>
                            <span class="btn btn-success btn-block disabled">Job Fully Completed</span>
                        </td>
                    <% else %>
                        <td>
                            <span class="btn btn-block disabled">Unknown Status</span>
                        </td>
                    <% end %>

                </tr>
            <% end %>
        <tbody>
      </table>

      <% else %>
        <h4>You have not made any job offers. </h4>
        <br>
      <% end %>

    </div>
  </div>
</div>

app/views/recruits/new.html.erb
<div class="container">

  <div class="heading heading-contact">
    <div class="col-lg-12">
      <div class="section-heading">
        <h2>New Job Offer Information</h2>
      </div>
    </div>
  </div>

  <div class="heading col-lg-12">
    <h4>Username: <%= @posting.candidate.individual.username %> </h4>
    <h4>Skills: <%= @posting.candidate.language %> </h4>
    <h4>Rate ($/hr): <%= @posting.candidate.rate %> </h4>
  </div>

  <div class="row">
    <div class="col-md-9 personal-info">
        <!-- form for -->
                <%= form_for @new_recruit do |f| %>

                <% if @new_recruit.errors.any? %>
                <div id="error_explanation">
                    <h2><%= pluralize(@new_recruit.errors.count, "error") %>
                        prohibited this profile from being saved:</h2>

                    <ul>
                        <% @new_recruit.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                        <% end %>
                    </ul>
                </div>
                <% end %>

                <form class="form-horizontal" role="form">

                <!-- Text input-->
                <div class="form-group">
                    <%= f.label :'Job Scope', class:"col-lg-3 control-label" %>
                    <div class="col-md-8">
                        <%= f.text_field :scope, autofocus: true, class: "form-control", placeholder:"Brief Description of job scope", required: true %>
                        <br/>
                    </div>
                </div>
                <br>
                <br>

                <div class="form-group">

                  <%= f.label :'Start Date', class:"col-lg-3 control-label" %>
                  <div class="col-md-8">

                  <%= f.date_field :start_date, class: "form-control", required: true %>
                  <!-- <%= f.time_select :start_date, :ignore_date => true, class: "form-control" %> -->
                  </div>
                </div>
                <br>
                <br>

                <div class="form-group">

                  <%= f.label :'End Date', class:"col-lg-3 control-label" %>
                  <div class="col-md-8">

                  <%= f.date_field :end_date, class: "form-control", required: true %>
                  <!-- <%= f.time_select :end_date, :ignore_date => true, class: "form-control" %> -->
                  </div>
                </div>
                <br>
                <br>


                <p>
                    <%= f.hidden_field :posting_id, value: @posting.id %>
                </p>

                <p>
                    <%= f.hidden_field :company_id, value: current_user.id %>
                </p>


                <div class="form-group">
                    <label class="col-md-3 control-label"></label>
                    <div class="col-md-8">
                        <div class="pull-right">

                            <%= f.submit "Submit", Class: "btn btn-success" %>

                            <%= link_to "Cancel", :back, class: "btn btn-default" %>

                        </div>
                    </div>
                </div>

              </form>

              <% end %>

    </div>

</div>
    <!-- /.col-lg-12 -->
</div>
<br>
<br>